name: Upload exe application
on: push
jobs: 
  build-project:
    name: exe app
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: ocs-rc
      - name: zip content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: create release
        id: create-new-release
        uses: actions/create-release@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: ocs-rc-v${{ github.run_number }}.zip
          asset_content_type: application/zip
          
