name: Publish

on: push

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*'
        asset_name: mything
        tag: v2.0
        body: "This is my release text"
